"""コンテンツフィルターの閾値定数."""

# --- ホワイトアウト判定 ---
WHITEOUT_NEAR_WHITE_THRESHOLD: float = 0.92
WHITEOUT_LUMINANCE_ENTROPY_THRESHOLD: float = 0.55
WHITEOUT_BRIGHTNESS_THRESHOLD: float = 245.0
WHITEOUT_MAX_CONTRAST: float = 6.0
WHITEOUT_MAX_EDGE_DENSITY: float = 0.02
WHITEOUT_MIN_DOMINANT_TONE_RATIO: float = 0.88
WHITEOUT_BRIGHT_WASHOUT_THRESHOLD: float = 0.60
WHITEOUT_RELAXED_MIN_BRIGHTNESS: float = 200.0
WHITEOUT_RELAXED_MAX_CONTRAST: float = 8.0
WHITEOUT_RELAXED_MAX_EDGE_DENSITY: float = 0.05
WHITEOUT_LUMINANCE_RANGE_MIN: float = 12.0
WHITEOUT_RELAXED_MAX_VISIBILITY: float = 0.76

# --- ブラックアウト判定 ---
BLACKOUT_NEAR_BLACK_RATIO: float = 0.97
BLACKOUT_LUMINANCE_ENTROPY_MAX: float = 0.35

# --- 単色判定 ---
SINGLE_TONE_DOMINANT_RATIO: float = 0.88
SINGLE_TONE_MAX_EXTREME_RATIO: float = 0.25

# --- フェード遷移判定（直接） ---
DIRECT_FADE_NEAR_WHITE_THRESHOLD: float = 0.28
DIRECT_FADE_NEAR_BLACK_THRESHOLD: float = 0.28
DIRECT_FADE_BRIGHTNESS_THRESHOLD: float = 200.0
DIRECT_FADE_DARKNESS_THRESHOLD: float = 58.0
DIRECT_FADE_MAX_CONTRAST: float = 12.0
DIRECT_FADE_MAX_EDGE_DENSITY: float = 0.08
DIRECT_FADE_MIN_DOMINANT_TONE_RATIO: float = 0.72
DIRECT_FADE_MIN_LUMINANCE_RANGE: float = 28.0
FADE_VISIBILITY_THRESHOLD: float = 0.30
FADE_INFORMATION_THRESHOLD: float = 0.35

# --- 明るい洗い流しフェード判定 ---
BRIGHT_WASHOUT_FADE_THRESHOLD: float = 0.54
BRIGHT_WASHOUT_FADE_MIN_BRIGHTNESS: float = 185.0
BRIGHT_WASHOUT_FADE_MIN_NEAR_WHITE_RATIO: float = 0.24
BRIGHT_WASHOUT_FADE_MAX_VISIBILITY: float = 0.68
BRIGHT_WASHOUT_FADE_MAX_INFORMATION: float = 0.55

# --- ベールフェード判定 ---
VEILED_FADE_THRESHOLD: float = 0.46
VEILED_FADE_MIN_BRIGHT_WASHOUT: float = 0.40
VEILED_FADE_MIN_EXTREME_RATIO: float = 0.20
VEILED_FADE_MIN_SYSTEM_UI: float = 0.20

# --- 明白フェード（obvious_fade） ---
OBVIOUS_FADE_EXTREME_RATIO: float = 0.65

# --- 相対遷移スコアによるフェード判定 ---
RELATIVE_BRIGHT_TRANSITION_THRESHOLD: float = 0.56
RELATIVE_BRIGHT_VISIBILITY_MAX: float = 0.78
RELATIVE_BRIGHT_INFORMATION_MAX: float = 0.62
RELATIVE_BRIGHT_WASHOUT_MIN: float = 0.24
RELATIVE_BRIGHT_EXTREME_THRESHOLD: float = 0.58
RELATIVE_BRIGHT_EXTREME_TRANSITION: float = 0.72
RELATIVE_DARK_TRANSITION_THRESHOLD: float = 0.54
RELATIVE_DARK_VISIBILITY_MAX: float = 0.66

# --- 時間的遷移（temporal） ---
TEMPORAL_SIMILARITY_THRESHOLD: float = 0.88
TEMPORAL_VISIBILITY_MARGIN: float = 0.18

# --- 輝度レンジ最小値 ---
LUMINANCE_RANGE_P10_MIN: float = 12.0
LUMINANCE_RANGE_P25_MIN: float = 14.0
