"""遷移フレーム判定の閾値・重み定数."""

# --- 明るい洗い流しスコア ---
BRIGHT_WASHOUT_BRIGHTNESS_BASE: float = 180.0
BRIGHT_WASHOUT_BRIGHTNESS_SCALE: float = 75.0
BRIGHT_WASHOUT_CONTRAST_SCALE: float = 18.0
BRIGHT_WASHOUT_EDGE_SCALE: float = 0.14
BRIGHT_WASHOUT_RANGE_SCALE: float = 48.0
BRIGHT_WASHOUT_WEIGHT_BRIGHTNESS: float = 0.25
BRIGHT_WASHOUT_WEIGHT_NEAR_WHITE: float = 0.20
BRIGHT_WASHOUT_WEIGHT_CONTRAST: float = 0.20
BRIGHT_WASHOUT_WEIGHT_EDGE: float = 0.15
BRIGHT_WASHOUT_WEIGHT_DOMINANT: float = 0.10
BRIGHT_WASHOUT_WEIGHT_RANGE: float = 0.10

# --- サポートUI スコア ---
SUPPORT_UI_DENSITY_WEIGHT: float = 0.65
SUPPORT_UI_ACTION_INVERSE_WEIGHT: float = 0.35

# --- ベール遷移スコア ---
VEILED_VISIBILITY_INVERSE_WEIGHT: float = 0.18
VEILED_INFORMATION_INVERSE_WEIGHT: float = 0.16
VEILED_EXPOSURE_EXTREME_WEIGHT: float = 0.12
VEILED_RANGE_PENALTY_WEIGHT: float = 0.10
VEILED_CONTRAST_PENALTY_WEIGHT: float = 0.10
VEILED_EDGE_PENALTY_WEIGHT: float = 0.08
VEILED_BRIGHT_WASHOUT_WEIGHT: float = 0.10
VEILED_SYSTEM_UI_WEIGHT: float = 0.08
VEILED_SUPPORT_UI_WEIGHT: float = 0.08

# --- 相対遷移スコア ---
RELATIVE_TAIL_WIDTH_MIN: float = 8.0
RELATIVE_BRIGHT_OUTLIER_SCALE: float = 0.18
RELATIVE_DARK_OUTLIER_SCALE: float = 0.18
RELATIVE_NEAR_WHITE_FLOOR: float = 0.05
RELATIVE_NEAR_BLACK_FLOOR: float = 0.05
RELATIVE_DOMINANT_TONE_FLOOR: float = 0.55
RELATIVE_DOMINANT_TONE_SCALE: float = 0.20

# --- 構造欠損スコア ---
STRUCTURE_CONTRAST_WEIGHT: float = 0.40
STRUCTURE_EDGE_WEIGHT: float = 0.35
STRUCTURE_RANGE_WEIGHT: float = 0.25

# --- 相対明転スコア ---
RELATIVE_BRIGHT_OUTLIER_WEIGHT: float = 0.35
RELATIVE_BRIGHT_NEAR_WHITE_WEIGHT: float = 0.25
RELATIVE_BRIGHT_WASHOUT_WEIGHT: float = 0.20
RELATIVE_BRIGHT_STRUCTURE_WEIGHT: float = 0.20

# --- 相対暗転スコア ---
RELATIVE_DARK_OUTLIER_WEIGHT: float = 0.40
RELATIVE_DARK_NEAR_BLACK_WEIGHT: float = 0.25
RELATIVE_DARK_DOMINANT_WEIGHT: float = 0.20
RELATIVE_DARK_STRUCTURE_WEIGHT: float = 0.15
